# Generated by Django 5.1.6 on 2026-03-27 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_position_catalog_and_entry_metadata(apps, schema_editor):
    Position = apps.get_model("recruitment", "Position")
    PositionPosting = apps.get_model("recruitment", "PositionPosting")

    for entry in PositionPosting.objects.all():
        position, _created = Position.objects.get_or_create(
            position_code=f"POS-{entry.job_code}",
            defaults={
                "title": entry.title or entry.job_code,
                "unit": entry.unit or "Unassigned Unit",
                "description": entry.description or "Imported position description.",
                "requirements": entry.requirements or "Imported position requirements.",
                "qualification_reference": "",
                "is_active": entry.is_active,
            },
        )

        entry.position_reference = position
        if entry.branch == "plantilla":
            entry.intake_mode = "fixed_period"
            if not entry.closing_date:
                entry.closing_date = entry.opening_date
        else:
            entry.intake_mode = "opening_based" if entry.closing_date else "pooling"
        entry.status = "active" if entry.is_active else "closed"
        entry.qualification_reference = entry.qualification_reference or ""
        entry.save(
            update_fields=[
                "position_reference",
                "intake_mode",
                "status",
                "closing_date",
                "qualification_reference",
            ]
        )


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_alter_auditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position_code', models.CharField(max_length=30, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('qualification_reference', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title', 'position_code'],
            },
        ),
        migrations.AlterModelOptions(
            name='positionposting',
            options={'ordering': ['title'], 'verbose_name': 'Recruitment Entry', 'verbose_name_plural': 'Recruitment Entries'},
        ),
        migrations.AddField(
            model_name='positionposting',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_recruitment_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='positionposting',
            name='intake_mode',
            field=models.CharField(choices=[('fixed_period', 'Fixed Period'), ('opening_based', 'Opening Based'), ('continuous', 'Continuous'), ('pooling', 'Pooling')], default='fixed_period', max_length=30),
        ),
        migrations.AddField(
            model_name='positionposting',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='positionposting',
            name='qualification_reference',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='positionposting',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='positionposting',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_recruitment_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_submitted', 'Application Submitted'), ('routed', 'Application Routed'), ('decision_recorded', 'Decision Recorded'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='positionposting',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='positionposting',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='positionposting',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='positionposting',
            name='unit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='positionposting',
            name='position_reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recruitment_entries', to='recruitment.position'),
        ),
        migrations.RunPython(
            backfill_position_catalog_and_entry_metadata,
            migrations.RunPython.noop,
        ),
    ]
