# Generated by Django 5.1.6 on 2026-03-27 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('decision_recorded', 'Decision Recorded'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.CreateModel(
            name='RecruitmentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('current_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('current_handler_role', models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('secretariat', 'Secretariat'), ('hrm_chief', 'HRM Chief'), ('hrmpsb_member', 'HRMPSB Member'), ('appointing_authority', 'Appointing Authority'), ('system_admin', 'System Administrator')], max_length=40)),
                ('case_status', models.CharField(choices=[('active', 'Active'), ('returned_to_applicant', 'Returned to Applicant'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='active', max_length=40)),
                ('is_stage_locked', models.BooleanField(default=False)),
                ('locked_stage', models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case', to='recruitment.recruitmentapplication')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
