# Generated by Django 5.1.6 on 2026-03-27 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_alter_auditlog_action_recruitmentcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('route_type', models.CharField(choices=[('initial', 'Initial Routing'), ('forward', 'Forward Routing'), ('override', 'Override Routing'), ('reopen', 'Reopen Routing')], max_length=20)),
                ('from_handler_role', models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('secretariat', 'Secretariat'), ('hrm_chief', 'HRM Chief'), ('hrmpsb_member', 'HRMPSB Member'), ('appointing_authority', 'Appointing Authority'), ('system_admin', 'System Administrator')], max_length=40)),
                ('to_handler_role', models.CharField(blank=True, choices=[('applicant', 'Applicant'), ('secretariat', 'Secretariat'), ('hrm_chief', 'HRM Chief'), ('hrmpsb_member', 'HRMPSB Member'), ('appointing_authority', 'Appointing Authority'), ('system_admin', 'System Administrator')], max_length=40)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('returned_to_applicant', 'Returned to Applicant'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=40)),
                ('to_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('returned_to_applicant', 'Returned to Applicant'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=40)),
                ('from_stage', models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('to_stage', models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('description', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('is_override', models.BooleanField(default=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='routing_history_actions', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_history', to='recruitment.recruitmentapplication')),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_history', to='recruitment.recruitmentcase')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
