# Generated by Django 5.1.6 on 2026-03-29 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_auditlog_action_examrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('decision_recorded', 'Decision Recorded'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('triggered_by_role', models.CharField(blank=True, max_length=40)),
                ('notification_type', models.CharField(choices=[('submission_acknowledgment', 'Submission Acknowledgment'), ('selected_applicant', 'Selected Applicant Notification'), ('non_selected_applicant', 'Non-selected Applicant Notification'), ('requirement_checklist', 'Requirement Checklist Notification'), ('reminder', 'Reminder Notification')], max_length=40)),
                ('delivery_channel', models.CharField(choices=[('email', 'Email')], default='email', max_length=20)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('related_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('returned_to_applicant', 'Returned to Applicant'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], max_length=40)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('failure_details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recruitment.recruitmentapplication')),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='recruitment.recruitmentcase')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
