# Generated by Django 5.1.6 on 2026-03-29 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_notification_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('decision_recorded', 'Decision Recorded'), ('completion_recorded', 'Completion Recorded'), ('case_closed', 'Case Closed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='examrecord',
            name='review_stage',
            field=models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='recruitmentcase',
            name='current_stage',
            field=models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='recruitmentcase',
            name='locked_stage',
            field=models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='routinghistory',
            name='from_stage',
            field=models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='routinghistory',
            name='route_type',
            field=models.CharField(choices=[('initial', 'Initial Routing'), ('forward', 'Forward Routing'), ('override', 'Override Routing'), ('reopen', 'Reopen Routing'), ('close', 'Case Closure')], max_length=20),
        ),
        migrations.AlterField(
            model_name='routinghistory',
            name='to_stage',
            field=models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='screeningrecord',
            name='review_stage',
            field=models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.CreateModel(
            name='CompletionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracked_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('completion_reference', models.CharField(blank=True, max_length=255)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('announcement_reference', models.CharField(blank=True, max_length=255)),
                ('announcement_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='recruitment.recruitmentapplication')),
                ('recruitment_case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_record', to='recruitment.recruitmentcase')),
                ('tracked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='completion_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompletionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_label', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not_applicable', 'Not Applicable')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('completion_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='recruitment.completionrecord')),
            ],
            options={
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
