# Generated by Django 5.1.6 on 2026-03-28 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_recruitmentapplication_performance_rating_and_evidence_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencevaultitem',
            name='recruitment_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='recruitment.recruitmentcase'),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='workflow_stage',
            field=models.CharField(blank=True, choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('interview_scheduled', 'Interview Scheduled'), ('interview_finalized', 'Interview Finalized'), ('interview_rating_recorded', 'Interview Rating Recorded'), ('interview_fallback_uploaded', 'Interview Fallback Uploaded'), ('decision_recorded', 'Decision Recorded'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('scheduled_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('scheduled_for', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('session_notes', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='recruitment.recruitmentapplication')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_sessions', to='recruitment.positionposting')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['review_stage', 'scheduled_for', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('rated_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('rating_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_notes', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_ratings', to='recruitment.recruitmentapplication')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_ratings', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_ratings', to='recruitment.recruitmentcase')),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recruitment.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='interviewsession',
            constraint=models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_interview_session_per_application_stage'),
        ),
        migrations.AddConstraint(
            model_name='interviewrating',
            constraint=models.UniqueConstraint(fields=('interview_session', 'rated_by'), name='unique_interview_rating_per_session_evaluator'),
        ),
    ]
