# Generated by Django 5.1.6 on 2026-03-29 06:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models
from django.utils.text import slugify


def _build_document_key(label, pk):
    normalized = slugify(label or "")
    return normalized[:150] or f"artifact-{pk}"


def backfill_evidence_vault_metadata(apps, schema_editor):
    EvidenceVaultItem = apps.get_model("recruitment", "EvidenceVaultItem")
    RecruitmentApplication = apps.get_model("recruitment", "RecruitmentApplication")
    RecruitmentCase = apps.get_model("recruitment", "RecruitmentCase")
    RecruitmentUser = apps.get_model("recruitment", "RecruitmentUser")

    applications_by_id = {
        application.id: application
        for application in RecruitmentApplication.objects.all().only("id", "submitted_at")
    }
    cases_by_application = {
        case.application_id: case
        for case in RecruitmentCase.objects.all().only("id", "application_id", "current_stage")
    }
    users_by_id = {
        user.id: user
        for user in RecruitmentUser.objects.all().only("id", "role")
    }

    grouped_items = {}
    for item in EvidenceVaultItem.objects.all().order_by("application_id", "created_at", "id"):
        application = applications_by_id.get(item.application_id)
        case = cases_by_application.get(item.application_id)
        if application and application.submitted_at and item.created_at <= application.submitted_at:
            stage = "applicant_intake"
        else:
            stage = case.current_stage if case and case.current_stage else "applicant_intake"
        document_key = _build_document_key(item.label, item.pk)
        grouped_items.setdefault((item.application_id, stage, document_key), []).append((item, case, stage, document_key))

    for grouped in grouped_items.values():
        version_family = uuid.uuid4()
        previous_item = None
        group_count = len(grouped)
        for index, (item, case, stage, document_key) in enumerate(grouped, start=1):
            uploaded_by = users_by_id.get(item.uploaded_by_id)
            archived_by = users_by_id.get(item.archived_by_id)
            item.recruitment_case_id = case.id if case else None
            item.stage = stage
            item.uploaded_by_role = uploaded_by.role if uploaded_by else ""
            item.archived_by_role = archived_by.role if archived_by else ""
            item.document_key = document_key
            item.version_family = version_family
            item.version_number = index
            item.previous_version_id = previous_item.id if previous_item else None
            item.is_current_version = index == group_count
            item.digest_algorithm = item.digest_algorithm or "sha256"
            item.save(
                update_fields=[
                    "recruitment_case",
                    "stage",
                    "uploaded_by_role",
                    "archived_by_role",
                    "document_key",
                    "version_family",
                    "version_number",
                    "previous_version",
                    "is_current_version",
                    "digest_algorithm",
                ]
            )
            previous_item = item


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_alter_auditlog_action_alter_examrecord_review_stage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencevaultitem',
            name='archive_tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='archived_by_role',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='digest_algorithm',
            field=models.CharField(default='sha256', max_length=20),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='document_key',
            field=models.CharField(db_index=True, default='', editable=False, max_length=150),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='is_current_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='recruitment.evidencevaultitem'),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='recruitment_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='recruitment.recruitmentcase'),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='stage',
            field=models.CharField(choices=[('applicant_intake', 'Applicant Intake'), ('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], default='applicant_intake', max_length=40),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='uploaded_by_role',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='version_family',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='evidencevaultitem',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('decision_recorded', 'Decision Recorded'), ('completion_recorded', 'Completion Recorded'), ('case_closed', 'Case Closed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('evidence_archived', 'Evidence Archived'), ('evidence_restored', 'Evidence Restored'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.RunPython(backfill_evidence_vault_metadata, noop_reverse),
        migrations.AddIndex(
            model_name='evidencevaultitem',
            index=models.Index(fields=['application', 'stage', 'document_key'], name='recruitment_applica_1d3765_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencevaultitem',
            index=models.Index(fields=['is_archived', 'stage'], name='recruitment_is_arch_698f8f_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencevaultitem',
            constraint=models.UniqueConstraint(fields=('version_family', 'version_number'), name='unique_evidence_version_per_family'),
        ),
    ]
