# Generated by Django 5.1.6 on 2026-03-28 08:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_evidencevaultitem_recruitment_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('interview_scheduled', 'Interview Scheduled'), ('interview_finalized', 'Interview Finalized'), ('interview_rating_recorded', 'Interview Rating Recorded'), ('interview_fallback_uploaded', 'Interview Fallback Uploaded'), ('deliberation_recorded', 'Deliberation Recorded'), ('deliberation_finalized', 'Deliberation Finalized'), ('car_generated', 'Comparative Assessment Report Generated'), ('car_finalized', 'Comparative Assessment Report Finalized'), ('decision_recorded', 'Decision Recorded'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.CreateModel(
            name='ComparativeAssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('generated_by_role', models.CharField(blank=True, max_length=40)),
                ('summary_notes', models.TextField(blank=True)),
                ('consolidated_snapshot', models.JSONField(blank=True, default=dict)),
                ('generation_count', models.PositiveIntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_reports', to='recruitment.recruitmentapplication')),
                ('evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparative_assessment_reports', to='recruitment.evidencevaultitem')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_comparative_assessment_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_comparative_assessment_reports', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_reports', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_reports', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['review_stage', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliberationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], max_length=40)),
                ('recorded_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('deliberated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliberation_minutes', models.TextField()),
                ('decision_support_summary', models.TextField()),
                ('ranking_position', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_notes', models.TextField(blank=True)),
                ('consolidated_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_records', to='recruitment.recruitmentapplication')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_deliberation_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_deliberation_records', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_records', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliberation_records', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['review_stage', 'deliberated_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparativeAssessmentReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_order', models.PositiveIntegerField()),
                ('qualification_outcome', models.CharField(blank=True, max_length=40)),
                ('exam_status', models.CharField(blank=True, max_length=20)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('interview_average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decision_support_summary', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_report_items', to='recruitment.recruitmentapplication')),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_report_items', to='recruitment.recruitmentcase')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recruitment.comparativeassessmentreport')),
                ('deliberation_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparative_assessment_report_items', to='recruitment.deliberationrecord')),
            ],
            options={
                'ordering': ['rank_order', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreport',
            constraint=models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_car_per_application_stage'),
        ),
        migrations.AddConstraint(
            model_name='deliberationrecord',
            constraint=models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_deliberation_record_per_application_stage'),
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreportitem',
            constraint=models.UniqueConstraint(fields=('report', 'application'), name='unique_car_item_per_report_application'),
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreportitem',
            constraint=models.UniqueConstraint(fields=('report', 'rank_order'), name='unique_car_rank_per_report'),
        ),
    ]
