# Generated by Django 5.1.6 on 2026-03-28 09:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_auditlog_action_comparativeassessmentreport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('closed', 'Closed')], default='appointing_authority_review', max_length=40)),
                ('decided_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('decision_outcome', models.CharField(choices=[('selected', 'Selected'), ('not_selected', 'Not Selected')], max_length=20)),
                ('decision_notes', models.TextField()),
                ('submission_packet_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_decisions', to='recruitment.recruitmentapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_final_decisions', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_decisions', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_decisions', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['-decided_at', '-created_at'],
            },
        ),
    ]
