# Generated by Django 5.1.6 on 2026-03-29 08:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_evidencevaultitem_archive_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('internal_login', 'Internal Login'), ('internal_logout', 'Internal Logout'), ('password_changed', 'Password Changed'), ('internal_account_created', 'Internal Account Created'), ('internal_account_updated', 'Internal Account Updated'), ('internal_account_activated', 'Internal Account Activated'), ('internal_account_deactivated', 'Internal Account Deactivated'), ('internal_role_changed', 'Internal Role Changed'), ('position_created', 'Position Created'), ('position_updated', 'Position Updated'), ('recruitment_entry_created', 'Recruitment Entry Created'), ('recruitment_entry_updated', 'Recruitment Entry Updated'), ('recruitment_entry_status_changed', 'Recruitment Entry Status Changed'), ('application_created', 'Application Created'), ('application_updated', 'Application Updated'), ('application_otp_sent', 'Application OTP Sent'), ('application_otp_verified', 'Application OTP Verified'), ('application_submitted', 'Application Submitted'), ('case_created', 'Case Created'), ('case_reopened', 'Case Reopened'), ('routed', 'Application Routed'), ('screening_recorded', 'Screening Recorded'), ('screening_finalized', 'Screening Finalized'), ('exam_recorded', 'Exam Recorded'), ('exam_finalized', 'Exam Finalized'), ('interview_scheduled', 'Interview Scheduled'), ('interview_finalized', 'Interview Finalized'), ('interview_rating_recorded', 'Interview Rating Recorded'), ('interview_fallback_uploaded', 'Interview Fallback Uploaded'), ('deliberation_recorded', 'Deliberation Recorded'), ('deliberation_finalized', 'Deliberation Finalized'), ('car_generated', 'Comparative Assessment Report Generated'), ('car_finalized', 'Comparative Assessment Report Finalized'), ('decision_recorded', 'Decision Recorded'), ('completion_recorded', 'Completion Recorded'), ('case_closed', 'Case Closed'), ('notification_sent', 'Notification Sent'), ('notification_failed', 'Notification Failed'), ('override_granted', 'Override Granted'), ('override_used', 'Override Used'), ('evidence_uploaded', 'Evidence Uploaded'), ('evidence_downloaded', 'Evidence Downloaded'), ('evidence_archived', 'Evidence Archived'), ('evidence_restored', 'Evidence Restored'), ('export_generated', 'Export Generated')], max_length=50),
        ),
        migrations.CreateModel(
            name='ComparativeAssessmentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('generated_by_role', models.CharField(blank=True, max_length=40)),
                ('summary_notes', models.TextField(blank=True)),
                ('consolidated_snapshot', models.JSONField(blank=True, default=dict)),
                ('generation_count', models.PositiveIntegerField(default=1)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_reports', to='recruitment.recruitmentapplication')),
                ('evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comparative_assessment_reports', to='recruitment.evidencevaultitem')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_comparative_assessment_reports', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_comparative_assessment_reports', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_reports', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_reports', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['review_stage', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliberationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40)),
                ('recorded_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('deliberated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deliberation_minutes', models.TextField()),
                ('decision_support_summary', models.TextField()),
                ('ranking_position', models.PositiveIntegerField(blank=True, null=True)),
                ('ranking_notes', models.TextField(blank=True)),
                ('consolidated_snapshot', models.JSONField(blank=True, default=dict)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_records', to='recruitment.recruitmentapplication')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_deliberation_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_deliberation_records', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliberation_records', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliberation_records', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['review_stage', 'deliberated_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComparativeAssessmentReportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rank_order', models.PositiveIntegerField()),
                ('qualification_outcome', models.CharField(blank=True, max_length=40)),
                ('exam_status', models.CharField(blank=True, max_length=20)),
                ('exam_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('interview_average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('decision_support_summary', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_report_items', to='recruitment.recruitmentapplication')),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparative_assessment_report_items', to='recruitment.recruitmentcase')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recruitment.comparativeassessmentreport')),
                ('deliberation_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comparative_assessment_report_items', to='recruitment.deliberationrecord')),
            ],
            options={
                'ordering': ['rank_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinalDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], default='appointing_authority_review', max_length=40)),
                ('decided_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('decision_outcome', models.CharField(choices=[('selected', 'Selected'), ('not_selected', 'Not Selected')], max_length=20)),
                ('decision_notes', models.TextField()),
                ('submission_packet_snapshot', models.JSONField(blank=True, default=dict)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_decisions', to='recruitment.recruitmentapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_final_decisions', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_decisions', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='final_decisions', to='recruitment.positionposting')),
            ],
            options={
                'ordering': ['-decided_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40)),
                ('scheduled_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('scheduled_for', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('session_notes', models.TextField(blank=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('finalized_by_role', models.CharField(blank=True, max_length=40)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='recruitment.recruitmentapplication')),
                ('finalized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_interview_sessions', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='recruitment.recruitmentcase')),
                ('recruitment_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='interview_sessions', to='recruitment.positionposting')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_interview_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['review_stage', 'scheduled_for', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_stage', models.CharField(choices=[('secretariat_review', 'Secretariat Review'), ('hrm_chief_review', 'HRM Chief Review'), ('hrmpsb_review', 'HRMPSB Review'), ('appointing_authority_review', 'Appointing Authority Review'), ('completion', 'Completion Tracking'), ('closed', 'Closed')], max_length=40)),
                ('rated_by_role', models.CharField(blank=True, max_length=40)),
                ('branch', models.CharField(choices=[('plantilla', 'Plantilla'), ('cos', 'COS')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1'), (2, 'Level 2')])),
                ('rating_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating_notes', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_ratings', to='recruitment.recruitmentapplication')),
                ('rated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interview_ratings', to=settings.AUTH_USER_MODEL)),
                ('recruitment_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_ratings', to='recruitment.recruitmentcase')),
                ('interview_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recruitment.interviewsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreport',
            constraint=models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_car_per_application_stage'),
        ),
        migrations.AddConstraint(
            model_name='deliberationrecord',
            constraint=models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_deliberation_record_per_application_stage'),
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreportitem',
            constraint=models.UniqueConstraint(fields=('report', 'application'), name='unique_car_item_per_report_application'),
        ),
        migrations.AddConstraint(
            model_name='comparativeassessmentreportitem',
            constraint=models.UniqueConstraint(fields=('report', 'rank_order'), name='unique_car_rank_per_report'),
        ),
        migrations.AddConstraint(
            model_name='interviewsession',
            constraint=models.UniqueConstraint(fields=('application', 'review_stage'), name='unique_interview_session_per_application_stage'),
        ),
        migrations.AddConstraint(
            model_name='interviewrating',
            constraint=models.UniqueConstraint(fields=('interview_session', 'rated_by'), name='unique_interview_rating_per_session_evaluator'),
        ),
    ]
