# Generated by Django 5.1.6 on 2026-03-29 18:25

from django.db import migrations, models


SENSITIVE_ACTIONS = {
    "case_reopened",
    "export_generated",
    "evidence_downloaded",
    "override_granted",
    "override_used",
    "protected_record_viewed",
    "evidence_vault_viewed",
    "audit_log_viewed",
}


def backfill_audit_log_traceability(apps, schema_editor):
    AuditLog = apps.get_model("recruitment", "AuditLog")
    for log in AuditLog.objects.select_related("application", "actor").all():
        metadata = log.metadata if isinstance(log.metadata, dict) else {}
        workflow_stage = ""
        for key in ("to_stage", "case_stage", "review_stage", "stage"):
            value = metadata.get(key)
            if value:
                workflow_stage = value
                break
        actor_role = log.actor_role or ""
        if log.actor_id and not actor_role:
            actor_role = getattr(log.actor, "role", "") or ""
        case_reference = log.case_reference or ""
        if log.application_id and not case_reference:
            case_reference = getattr(log.application, "reference_number", "") or ""
        AuditLog.objects.filter(pk=log.pk).update(
            actor_role=actor_role,
            case_reference=case_reference,
            workflow_stage=workflow_stage or log.workflow_stage or "",
            is_sensitive_access=log.action in SENSITIVE_ACTIONS or log.is_sensitive_access,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0013_alter_auditlog_action_comparativeassessmentreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="case_reference",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="is_sensitive_access",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="workflow_stage",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("internal_login", "Internal Login"),
                    ("internal_logout", "Internal Logout"),
                    ("password_changed", "Password Changed"),
                    ("internal_account_created", "Internal Account Created"),
                    ("internal_account_updated", "Internal Account Updated"),
                    ("internal_account_activated", "Internal Account Activated"),
                    ("internal_account_deactivated", "Internal Account Deactivated"),
                    ("internal_role_changed", "Internal Role Changed"),
                    ("position_created", "Position Created"),
                    ("position_updated", "Position Updated"),
                    ("recruitment_entry_created", "Recruitment Entry Created"),
                    ("recruitment_entry_updated", "Recruitment Entry Updated"),
                    ("recruitment_entry_status_changed", "Recruitment Entry Status Changed"),
                    ("application_created", "Application Created"),
                    ("application_updated", "Application Updated"),
                    ("application_otp_sent", "Application OTP Sent"),
                    ("application_otp_verified", "Application OTP Verified"),
                    ("application_submitted", "Application Submitted"),
                    ("case_created", "Case Created"),
                    ("case_reopened", "Case Reopened"),
                    ("routed", "Application Routed"),
                    ("screening_recorded", "Screening Recorded"),
                    ("screening_finalized", "Screening Finalized"),
                    ("exam_recorded", "Exam Recorded"),
                    ("exam_finalized", "Exam Finalized"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_finalized", "Interview Finalized"),
                    ("interview_rating_recorded", "Interview Rating Recorded"),
                    ("interview_fallback_uploaded", "Interview Fallback Uploaded"),
                    ("deliberation_recorded", "Deliberation Recorded"),
                    ("deliberation_finalized", "Deliberation Finalized"),
                    ("car_generated", "Comparative Assessment Report Generated"),
                    ("car_finalized", "Comparative Assessment Report Finalized"),
                    ("decision_recorded", "Decision Recorded"),
                    ("completion_recorded", "Completion Recorded"),
                    ("case_closed", "Case Closed"),
                    ("notification_sent", "Notification Sent"),
                    ("notification_failed", "Notification Failed"),
                    ("override_granted", "Override Granted"),
                    ("override_used", "Override Used"),
                    ("evidence_uploaded", "Evidence Uploaded"),
                    ("evidence_downloaded", "Evidence Downloaded"),
                    ("evidence_archived", "Evidence Archived"),
                    ("evidence_restored", "Evidence Restored"),
                    ("protected_record_viewed", "Protected Record Viewed"),
                    ("evidence_vault_viewed", "Evidence Vault Viewed"),
                    ("audit_log_viewed", "Audit Log Viewed"),
                    ("export_generated", "Export Generated"),
                ],
                max_length=50,
            ),
        ),
        migrations.RunPython(backfill_audit_log_traceability, migrations.RunPython.noop),
    ]
