# Generated by Django 5.1.6 on 2026-04-09 11:02

import csv
from io import StringIO

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


STARTER_POSITION_REFERENCE_TSV = """Position Title\tSG\tLevel\tClass ID\tOS Code\tOccupational Service\tGroup
Accountant II\t16\t2nd Level\tA2\t02-FS\tFinancial Service\tAccounting
Accountant III\t19\t2nd Level\tA3\t02-FS\tFinancial Service\tAccounting
Administrative Aide I\t1\t1st Level\tADA1\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Aide III\t3\t1st Level\tADA3\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Aide IV\t4\t1st Level\tADA4\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Aide VI\t6\t1st Level\tADA6\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Assistant I\t7\t1st Level\tADAS1\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Assistant II\t8\t1st Level\tADAS2\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Assistant III\t9\t1st Level\tADAS3\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Assistant V\t11\t2nd Level\tADAS5\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Officer I\t10\t2nd Level\tADOF1\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Officer III\t14\t2nd Level\tADOF3\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Officer IV\t15\t2nd Level\tADOF4\t01-GA\tGeneral Administrative Service\tAdministrative
Administrative Officer V\t18\t2nd Level\tADOF5\t01-GA\tGeneral Administrative Service\tAdministrative
Attorney III\t21\t2nd Level\tATY3\t15-LJ\tLegal and Judicial Service\tLegal
Chief Administrative Officer\t24\t2nd Level\tCADOF\t01-GA\tGeneral Administrative Service\tAdministrative
Communications Equipment Operator III\t8\t1st Level\tCEO3\t05-TC\tTransport, Comm. & Public Utilities Service\tCommunications Equipment
Dentist III\t19\t2nd Level\tDENT3\t09-MH\tMedicine and Health Service\tDentistry
Development Management Officer III\t18\t2nd Level\tDMO3\t03-PS\tPlanning Service\tDevelopment Management
Development Management Officer IV\t22\t2nd Level\tDMO4\t03-PS\tPlanning Service\tDevelopment Management
Development Management Officer V\t24\t2nd Level\tDMO5\t03-PS\tPlanning Service\tDevelopment Management
Director IV\t28\t2nd Level\tDIR4\t18-ES\tExecutive Service\tExecutive
Dormitory Manager I\t10\t2nd Level\tDM1\t17-MS\tMiscellaneous Service\tDormitory Management
Engineer III\t19\t2nd Level\tENG3\t04-AE\tArchitecture and Engineering Service\tEngineering
Entomologist III\t18\t2nd Level\tENTO3\t13-MP\tMath, Physical & Biological Sciences Service\tEntomology
Food-Drug Regulation Officer III\t18\t2nd Level\tFDRO3\t09-MH\tMedicine and Health Service\tHealth and Sanitation
Health Education and Promotion Officer II\t14\t2nd Level\tHEPO2\t09-MH\tMedicine and Health Service\tHealth Education & Promotion
Health Education and Promotion Officer III\t18\t2nd Level\tHEPO3\t09-MH\tMedicine and Health Service\tHealth Education & Promotion
Health Program Researcher\t9\t2nd Level\tHRP\t09-MH\tMedicine and Health Service\tHealth Program Development
Laboratory Aide II\t4\t1st Level\tLABAID2\t13-MP\tMath, Physical & Biological Sciences Service\tLaboratory
Legal Assistant II\t10\t2nd Level\tLGAS2\t15-LJ\tLegal and Judicial Service\tLegal Assistance
Librarian I\t11\t2nd Level\tLBR1\t10-EL\tEducation, Library, Museum & Archival Service\tLibrary
Licensing Officer I\t11\t2nd Level\tLIOF1\t02-FS\tFinancial Service\tLicense Inspection
Licensing Officer II\t15\t2nd Level\tLIOF2\t02-FS\tFinancial Service\tLicense Inspection
Licensing Officer III\t18\t2nd Level\tLIOF3\t02-FS\tFinancial Service\tLicense Inspection
Licensing Officer V\t24\t2nd Level\tLIOF5\t02-FS\tFinancial Service\tLicense Inspection
Medical Officer III\t18\t2nd Level\tMDOF3\t09-MH\tMedicine and Health Service\tMedical
Medical Officer IV\t20\t2nd Level\tMDOF4\t09-MH\tMedicine and Health Service\tMedical
Medical Officer V\t22\t2nd Level\tMDOF5\t09-MH\tMedicine and Health Service\tMedical
Medical Technologist II\t15\t2nd Level\tMDTK2\t09-MH\tMedicine and Health Service\tMedical Technology
Medical Technologist IV\t20\t2nd Level\tMDTK4\t09-MH\tMedicine and Health Service\tMedical Technology
Midwife VI\t18\t2nd Level\tMDWF6\t09-MH\tMedicine and Health Service\tNursing
Nurse III\t16\t2nd Level\tNURS3\t09-MH\tMedicine and Health Service\tNursing
Nurse V\t20\t2nd Level\tNURS5\t09-MH\tMedicine and Health Service\tNursing
Nursing Attendant I\t4\t1st Level\tNATT1\t09-MH\tMedicine and Health Service\tNursing
Nutritionist-Dietitian IV\t20\t2nd Level\tND4\t09-MH\tMedicine and Health Service\tDietetics
Pharmacist III\t14\t2nd Level\tPH3\t09-MH\tMedicine and Health Service\tPharmacy
Planning Officer II\t15\t2nd Level\tPLO2\t03-PS\tPlanning Service\tPlanning
Rural Health Physician\t24\t2nd Level\tRHP\t09-MH\tMedicine and Health Service\tMedical
Security Guard I\t6\t1st Level\tSECG1\t14-DS\tDefense and Security Service\tGuard/Watchman
Senior Health Program Officer\t18\t2nd Level\tSRHPO\t09-MH\tMedicine and Health Service\tHealth Program Development
Statistician II\t16\t2nd Level\tSTAT2\t03-PS\tPlanning Service\tStatistics
Statistician III\t19\t2nd Level\tSTAT3\t03-PS\tPlanning Service\tStatistics
Supervising Administrative Officer\t22\t2nd Level\tSADOF\t01-GA\tGeneral Administrative Service\tAdministrative
Training Specialist II\t15\t2nd Level\tTRSP2\t01-GA\tGeneral Administrative Service\tHuman Resource Management
Training Specialist III\t18\t2nd Level\tTRSP3\t01-GA\tGeneral Administrative Service\tHuman Resource Management
"""

CORE_REFERENCE_FIELDS = (
    "position_title",
    "salary_grade",
    "level_classification",
    "class_id",
    "os_code",
    "occupational_service",
    "occupational_group",
)


def _starter_rows():
    return list(csv.DictReader(StringIO(STARTER_POSITION_REFERENCE_TSV), delimiter="\t"))


def _normalize_text(value):
    if value is None:
        return None
    value = value.strip()
    return value or None


def _parse_salary_grade(value):
    normalized = _normalize_text(value)
    return int(normalized) if normalized else None


def _normalize_level(value):
    normalized = (_normalize_text(value) or "").lower()
    if normalized in {"1st level", "first level"}:
        return "FIRST_LEVEL"
    if normalized in {"2nd level", "second level"}:
        return "SECOND_LEVEL"
    return None


def _build_unique_slug(title, used_slugs):
    base_slug = slugify(title or "") or "position-reference"
    slug = base_slug
    suffix = 2
    while slug in used_slugs:
        slug = f"{base_slug}-{suffix}"
        suffix += 1
    used_slugs.add(slug)
    return slug


def _derive_reference_status(values, *, has_warning=False):
    missing = [field_name for field_name in CORE_REFERENCE_FIELDS if values.get(field_name) in (None, "")]
    if missing:
        return "INCOMPLETE_REFERENCE"
    if has_warning:
        return "NEEDS_REVIEW"
    return "VERIFIED_REFERENCE"


def _compose_legacy_notes(legacy_position):
    lines = []
    if getattr(legacy_position, "description", ""):
        lines.append(f"Legacy description: {legacy_position.description}")
    if getattr(legacy_position, "requirements", ""):
        lines.append(f"Legacy requirements: {legacy_position.requirements}")
    if getattr(legacy_position, "qualification_reference", ""):
        lines.append(f"Legacy qualification reference: {legacy_position.qualification_reference}")
    return "\n".join(lines)


def _reference_values_from_starter(raw_row, legacy_position=None):
    raw_level = _normalize_text(raw_row.get("Level"))
    level_classification = _normalize_level(raw_level)
    values = {
        "position_title": _normalize_text(raw_row.get("Position Title")),
        "salary_grade": _parse_salary_grade(raw_row.get("SG")),
        "level_classification": level_classification,
        "class_id": _normalize_text(raw_row.get("Class ID")),
        "os_code": _normalize_text(raw_row.get("OS Code")),
        "occupational_service": _normalize_text(raw_row.get("Occupational Service")),
        "occupational_group": _normalize_text(raw_row.get("Group")),
        "is_active": legacy_position.is_active if legacy_position is not None else True,
        "notes": _compose_legacy_notes(legacy_position) if legacy_position is not None else "",
        "position_code": legacy_position.position_code if legacy_position is not None else None,
        "agency_item_number": None,
        "office_division_default": legacy_position.unit if legacy_position is not None else None,
        "qs_education": None,
        "qs_training": None,
        "qs_experience": None,
        "qs_eligibility": None,
        "employment_track_applicability": None,
    }
    values["reference_status"] = _derive_reference_status(
        values,
        has_warning=raw_level is not None and level_classification is None,
    )
    return values


def _reference_values_from_legacy_only(legacy_position):
    values = {
        "position_title": legacy_position.title,
        "salary_grade": None,
        "level_classification": None,
        "class_id": None,
        "os_code": None,
        "occupational_service": None,
        "occupational_group": None,
        "reference_status": "INCOMPLETE_REFERENCE",
        "is_active": legacy_position.is_active,
        "notes": _compose_legacy_notes(legacy_position),
        "position_code": legacy_position.position_code,
        "agency_item_number": None,
        "office_division_default": legacy_position.unit or None,
        "qs_education": None,
        "qs_training": None,
        "qs_experience": None,
        "qs_eligibility": None,
        "employment_track_applicability": None,
    }
    return values


def seed_position_references(apps, schema_editor):
    Position = apps.get_model("recruitment", "Position")
    PositionPosting = apps.get_model("recruitment", "PositionPosting")
    PositionReference = apps.get_model("recruitment", "PositionReference")

    starter_by_title = {
        row["Position Title"].strip().lower(): row
        for row in _starter_rows()
        if row.get("Position Title")
    }
    used_slugs = set(filter(None, PositionReference.objects.values_list("position_slug", flat=True)))

    legacy_positions = list(Position.objects.all().order_by("id"))
    for legacy_position in legacy_positions:
        starter_row = starter_by_title.get((legacy_position.title or "").strip().lower())
        if starter_row:
            values = _reference_values_from_starter(starter_row, legacy_position=legacy_position)
        else:
            values = _reference_values_from_legacy_only(legacy_position)
        values["position_slug"] = _build_unique_slug(values["position_title"], used_slugs)
        PositionReference.objects.create(id=legacy_position.id, **values)

    existing_titles = {
        (reference.position_title or "").strip().lower()
        for reference in PositionReference.objects.all()
        if reference.position_title
    }
    for starter_row in _starter_rows():
        position_title = _normalize_text(starter_row.get("Position Title"))
        if not position_title or position_title.lower() in existing_titles:
            continue
        values = _reference_values_from_starter(starter_row)
        values["position_slug"] = _build_unique_slug(values["position_title"], used_slugs)
        PositionReference.objects.create(**values)
        existing_titles.add(position_title.lower())

    for entry in PositionPosting.objects.all().order_by("id"):
        if not entry.position_reference_id:
            continue
        reference = PositionReference.objects.filter(id=entry.position_reference_id).first()
        if reference is None:
            continue
        updates = {}
        if reference.position_title and entry.title != reference.position_title:
            updates["title"] = reference.position_title
        routing_level = entry.level
        if reference.level_classification == "FIRST_LEVEL":
            routing_level = 1
        elif reference.level_classification == "SECOND_LEVEL":
            routing_level = 2
        if routing_level and entry.level != routing_level:
            updates["level"] = routing_level
        if not entry.unit and reference.office_division_default:
            updates["unit"] = reference.office_division_default
        if updates:
            PositionPosting.objects.filter(pk=entry.pk).update(**updates)


class Migration(migrations.Migration):

    dependencies = [
        ("recruitment", "0015_entry_scoped_car_alignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PositionReference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("position_title", models.CharField(max_length=255)),
                ("position_slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("salary_grade", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "level_classification",
                    models.CharField(
                        blank=True,
                        choices=[("FIRST_LEVEL", "First Level"), ("SECOND_LEVEL", "Second Level")],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("class_id", models.CharField(blank=True, max_length=50, null=True)),
                ("os_code", models.CharField(blank=True, max_length=50, null=True)),
                ("occupational_service", models.CharField(blank=True, max_length=255, null=True)),
                ("occupational_group", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "reference_status",
                    models.CharField(
                        choices=[
                            ("VERIFIED_REFERENCE", "Verified Reference"),
                            ("NEEDS_REVIEW", "Needs Review"),
                            ("INCOMPLETE_REFERENCE", "Incomplete Reference"),
                        ],
                        default="NEEDS_REVIEW",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("position_code", models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ("agency_item_number", models.CharField(blank=True, max_length=100, null=True)),
                ("office_division_default", models.CharField(blank=True, max_length=255, null=True)),
                ("qs_education", models.TextField(blank=True, null=True)),
                ("qs_training", models.TextField(blank=True, null=True)),
                ("qs_experience", models.TextField(blank=True, null=True)),
                ("qs_eligibility", models.TextField(blank=True, null=True)),
                ("employment_track_applicability", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "ordering": ["position_title", "salary_grade", "class_id"],
            },
        ),
        migrations.RunPython(seed_position_references, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="positionposting",
            name="position_reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="recruitment_entries",
                to="recruitment.positionreference",
            ),
        ),
        migrations.DeleteModel(
            name="Position",
        ),
    ]
