from django.contrib.auth import views as auth_views
from django.urls import path

from .entry_views import (
    PositionCatalogCreateView,
    PositionCatalogListView,
    PositionCatalogUpdateView,
    RecruitmentEntryCreateView,
    RecruitmentEntryListView,
    RecruitmentEntryStatusUpdateView,
    RecruitmentEntryUpdateView,
)
from .identity_views import (
    InternalLoginView,
    InternalPasswordChangeDoneView,
    InternalPasswordChangeView,
    InternalUserCreateView,
    InternalUserListView,
    InternalUserToggleActiveView,
    InternalUserUpdateView,
)
from .views import (
    AuditLogListView,
    ApplicationDetailView,
    ApplicationAuditLogView,
    ApplicationListView,
    CaseClosureView,
    ComparativeAssessmentReportView,
    CompletionTrackingView,
    DashboardView,
    DeliberationRecordView,
    EvidenceArchiveToggleView,
    EvidenceDownloadView,
    EvidenceUploadView,
    EvidenceVaultListView,
    ExaminationRecordView,
    ExportApplicationBundleView,
    FinalDecisionView,
    InterviewFallbackUploadView,
    InterviewRatingView,
    InterviewSessionView,
    PositionListView,
    ReminderNotificationView,
    RequirementChecklistNotificationView,
    ScreeningReviewView,
    WorkflowActionView,
    WorkflowOverrideView,
    WorkflowQueueView,
    WorkflowReopenView,
)


urlpatterns = [
    path("", DashboardView.as_view(), name="dashboard"),
    path("login/", InternalLoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path(
        "password/change/",
        InternalPasswordChangeView.as_view(),
        name="password-change",
    ),
    path(
        "password/change/done/",
        InternalPasswordChangeDoneView.as_view(),
        name="password-change-done",
    ),
    path("users/", InternalUserListView.as_view(), name="internal-user-list"),
    path("users/new/", InternalUserCreateView.as_view(), name="internal-user-create"),
    path("users/<int:pk>/edit/", InternalUserUpdateView.as_view(), name="internal-user-update"),
    path(
        "users/<int:pk>/toggle-active/",
        InternalUserToggleActiveView.as_view(),
        name="internal-user-toggle-active",
    ),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/catalog/", PositionCatalogListView.as_view(), name="position-catalog-list"),
    path("positions/catalog/new/", PositionCatalogCreateView.as_view(), name="position-catalog-create"),
    path(
        "positions/catalog/<int:pk>/edit/",
        PositionCatalogUpdateView.as_view(),
        name="position-catalog-update",
    ),
    path("entries/", RecruitmentEntryListView.as_view(), name="recruitment-entry-list"),
    path("entries/new/", RecruitmentEntryCreateView.as_view(), name="recruitment-entry-create"),
    path(
        "entries/<int:pk>/edit/",
        RecruitmentEntryUpdateView.as_view(),
        name="recruitment-entry-update",
    ),
    path(
        "entries/<int:pk>/status/<str:status>/",
        RecruitmentEntryStatusUpdateView.as_view(),
        name="recruitment-entry-status",
    ),
    path("applications/", ApplicationListView.as_view(), name="application-list"),
    path("applications/<int:pk>/", ApplicationDetailView.as_view(), name="application-detail"),
    path("applications/<int:pk>/audit/", ApplicationAuditLogView.as_view(), name="application-audit-log"),
    path("applications/<int:pk>/screening/", ScreeningReviewView.as_view(), name="screening-review"),
    path("applications/<int:pk>/exam/", ExaminationRecordView.as_view(), name="exam-review"),
    path("applications/<int:pk>/interview/", InterviewSessionView.as_view(), name="interview-session"),
    path("applications/<int:pk>/interview/rating/", InterviewRatingView.as_view(), name="interview-rating"),
    path(
        "applications/<int:pk>/interview/fallback/",
        InterviewFallbackUploadView.as_view(),
        name="interview-fallback-upload",
    ),
    path("applications/<int:pk>/deliberation/", DeliberationRecordView.as_view(), name="deliberation-record"),
    path(
        "applications/<int:pk>/comparative-assessment/",
        ComparativeAssessmentReportView.as_view(),
        name="comparative-assessment-report",
    ),
    path("applications/<int:pk>/final-decision/", FinalDecisionView.as_view(), name="final-decision-record"),
    path("applications/<int:pk>/completion/", CompletionTrackingView.as_view(), name="completion-tracking"),
    path("applications/<int:pk>/close/", CaseClosureView.as_view(), name="case-close"),
    path("evidence/", EvidenceVaultListView.as_view(), name="evidence-vault-list"),
    path(
        "applications/<int:pk>/notifications/checklist/",
        RequirementChecklistNotificationView.as_view(),
        name="notification-checklist",
    ),
    path(
        "applications/<int:pk>/notifications/reminder/",
        ReminderNotificationView.as_view(),
        name="notification-reminder",
    ),
    path("applications/<int:pk>/evidence/upload/", EvidenceUploadView.as_view(), name="evidence-upload"),
    path(
        "applications/<int:pk>/evidence/<int:evidence_pk>/download/",
        EvidenceDownloadView.as_view(),
        name="evidence-download",
    ),
    path(
        "applications/<int:pk>/evidence/<int:evidence_pk>/archive/",
        EvidenceArchiveToggleView.as_view(),
        name="evidence-archive-toggle",
    ),
    path("applications/<int:pk>/export/", ExportApplicationBundleView.as_view(), name="application-export"),
    path("audit/", AuditLogListView.as_view(), name="audit-log-list"),
    path("workflow/queue/", WorkflowQueueView.as_view(), name="workflow-queue"),
    path("workflow/<int:pk>/action/", WorkflowActionView.as_view(), name="workflow-action"),
    path("workflow/<int:pk>/override/", WorkflowOverrideView.as_view(), name="workflow-override"),
    path("workflow/<int:pk>/reopen/", WorkflowReopenView.as_view(), name="workflow-reopen"),
]
